### ISSUE TITLE
Future request

### ISSUE THREAD

**Issue by itProfi** [JasperG/bilight#1]
Hello, JasperG! Can i ask some new futures on you app:
1. Can you inplement NIGTH MODE button?
2. 100 % brigthness button (long pres on hard remote controller).
3. May you add configure app on start, that it is not wait 12 sec and not find IWiFiBox (for use it with wonderfull UPD gateaway - https://github.com/sidoh/esp8266_milight_hub) .
Thanks!

**Comment by JasperG** [comment]
Hi there,

Yes, sure, I will see what I can do once I find myself some spare time.

For night mode; What remote are you using? (I do not have such a button on my physical remote).
I'd just need a remote control number (FUT092 or any of the like), for reference.

Next weekend, maybe.

Thanks for the suggestions.

**Comment by speendo** [comment]
Hi!

Did you already implement point (3) on this list? I also would like to use your wonderful app with an esp8266_milight_hub

**Comment by JasperG** [comment]
Hello,

No, I did not. I vaguely remember looking into this, but, as I recall, from what I understood, the ESP8266 project at https://github.com/sidoh/esp8266_milight_hub comes with its own REST API, and thereby exposes a totally different way to send commands out to the lights.

I remember this totally left me confused as to what the actual question in point [3] was.
Furthermore, I do not have one of those boards, and felt uninterested to purchase one, as my personal set up works with the app as is.

So, would have been unable to test anything. I feel, yo,u would be the second out of a total of two people interested in this. So I didn't bother.

**Comment by speendo** [comment]
Hi!

Well, in fact no, the questionable project also supports the standard milight/limitlessled protocol. You can even choose between v5 and v6. When v6 is chosen, your app does already perfectly control my milght bulbs.

The only hassle is, that everytime I start your app, I have to reenter the IP address of my esp.

I *think* this has something to do with your app waiting for a response... from an already connected ibox.

The esp8266 seems to react differently to that (or doesn't react at all?) However, after entering the IP manually, everything works flawlessly.

**Comment by speendo** [comment]
Maybe this is even a better explanation?
https://github.com/sidoh/esp8266_milight_hub/issues/27#issuecomment-290340231

I don't really know, I do not yet understand too much of this whole thing :)

But maybe it's interesting for you that your App is quite a topic in the issues of esp8288_milight_hub

**Comment by JasperG** [comment]
Oh, if that's the case, it proves I did not at all understand the point.
It does, however, make me wonder what the advantage of such an esp-board would then be in the first place.

If all you want is to save an IP address, that - of course - can be done.

(Furthermore, as I once again vaguely remember, I thought the app would already save all external IP addresses entered.. - might have forgotten though.)

**Comment by speendo** [comment]
In fact the IP address seems to be saved but cannot be connected again. Maybe it's really something with the session ID?

Actually I found this whole esp project by chance. LimitlessLed announced a v7 bridge nearly one year ago. They promised that with the v7 bridges it would be possible to have more than 4 zones.

The announcement seems to be gone now, however, you can still find the text here:
https://community.home-assistant.io/t/limitlessled-wifi-bridge-v7-support/7147

I hoped that something similar to that is (or at least will be soon) possible with the esp8266 project...

**Comment by JasperG** [comment]
Do me a favor;

When launching the app; See if your IP is saved. More importantly; See the port number, and take note.

Then, reconnect, entering the IP again, like you said before. See if you get a connection (and IP) saved, at the same port number.

Because to me, the session id thing does not make sense.
The Bilight app tries to [get] a session id when connecting, first. It doesn't save them.

**Comment by JasperG** [comment]
Could it be, the ESP keeps a session alive, even when the mobile app assumes a new session id will be returned upon connecting?

To test; By manually entering the IP address in the app, can you connect to the ESP [more than once] without rebooting the ESP?

**Comment by speendo** [comment]
I made a screencast. It's uploading to youtube atm. I will send you the link once it's completed.
If that leaves any questions open, don't hesitate to ask.

**Comment by speendo** [comment]
Here it is:
https://youtu.be/-BE42lPp2zE

**Comment by JasperG** [comment]
Video has been removed.. (?)

**Comment by speendo** [comment]
Yes. Quite strange. The first of all my uploads that have been removed.
Can you write me a mail to milight@mailinator.com? I will then send you a private link to the video.

**Comment by JasperG** [comment]
I'd like to see it, yes. Can't you just paste a link here? (Unsure what you did to get it removed..?)

**Comment by speendo** [comment]
ok, left it on my own server (link expires on monday):
https://owncloud.yeara.net/s/OgIPy3jEHZLq6DV

And I'm unsure as well :)

**Comment by JasperG** [comment]
I'll make some changes. Check back in an hour or so.

**Comment by JasperG** [comment]
Pushed a new version to GP. Please confirm it now does what you need.

**Comment by speendo** [comment]
Nice! Works like a charm!

**Comment by JasperG** [comment]
speendo; If you are German ( I think you might be ), would you, and could you, please be so kind to translate https://github.com/JasperG/bilight/blob/master/bilight/src/main/res/values-de/strings.xml ?

Thank you!

**Comment by speendo** [comment]
Actually I am Austrian but I still feel capabe to do so.

Can you explain the task a little more?

* Would you like me to make a fork or is a gist enough for you?
* How does it come that parts of it is already translated?

**Comment by JasperG** [comment]
That's great, thanks!

Just press edit and commit a pull request for the file. Or, any other way you like.

And, to answer your question, I did parts using Google Translate, a long time ago.

**Comment by speendo** [comment]
By the way, I might come to the Netherlands in the near future (I live in Brussels atm, so it wouldn't be too far). If you would like to have an esp8266 controller for your milights (maybe to experiment with it) I might be able to bring you one (for free of course).

**Comment by speendo** [comment]
I uploaded the translation. Please note the commit text.

One thing to add is that I used the informal form of address. In case you prefer a more formal form I can change that.

**Comment by JasperG** [comment]
> If you would like to have an esp8266 controller for your milights (maybe to experiment with it) I might be able to bring you one

I might just absolutely love that. That might trigger me to add and change some things, as I've read the ESP project claims it can control 2^16 "zones". Not that I have that many lights, of course 🔢 Thanks. Drop me a line when you're in or around Amsterdam, that's a 6 km trip for me.

Your translation is perfect, thank you. I've committed it to GP, I'm sure you'll see it later in the day. Thanks again!

**Comment by speendo** [comment]
Hey @JasperG,

there is a 70 % chance I come to Amsterdam this weekend. I'll bring an ESP controller for you.

Are you there this weekend? Do we need another (faster) form of communication or is github fine?

**Comment by JasperG** [comment]
Hi @speendo,

Awesome! I will be around, just started the weekend-routine. Please send me an email jasper - a - jaspergoes - dot - nl . Will exchange either Whatsapp or Facebook messenger for faster communication.

Cheers!

**Comment by JasperG** [comment]
{ positive reply written @speendo and later removed for privacy reasons 👍 }

**Comment by pauleec** [comment]
Hi @JasperG and greetings from Sydney Australia. I am installing 45 RGB-CCT MiLight lights in a property here in Sydney Australia and am doing some testing with the new ESP based controller. I note that you specify the RGBWW as one of the types of Milight lighting types supported. Futlight released support for the RGBWW type in 2015 which was limited by only being able to operate in 4 zone configurations. The latest release of their lights has support for 8zone capable/supported RGB-CCT lights. Can you confirm that your app can support 8-zone configurations of the new Milight RGB-CCT lights? Does the app support the ESP 2*16 zone configuration that you mention and can the 2*16 zones be for ALL RGB-CCT/Full Colour light types?

Are you planning a release of your app for the IOS platform? Australia is a BIG user of IOS.

Thanks

Thanks

**Comment by JasperG** [comment]
@pauleec Hi there.

> Can you confirm that your app can support 8-zone configurations of the new Milight RGB-CCT lights? 

No, I can not confirm that - I have not tested.
A wild guess would be that those newer lights simply accept zone numbers bigger than 4.

You could test by blocking out the IF-sequence starting at [line 566 of ControlActivity](https://github.com/JasperG/bilight/blob/1d715de8342d88b094d2beac94e086d34fcc0be7/bilight/src/main/java/com/jaspergoes/bilight/ControlActivity.java#L566) and replacing it with `Controller.controlZones = new int[]{5,6,7,8};` to test controlling zones 5, 6, 7 and 8.

> Does the app support the ESP 216 zone configuration that you mention and can the 216 zones be for ALL RGB-CCT/Full Colour light types?

If 2^16 zones were to be supported (65535 zones), another byte must be added to each command. I have read the ESP already has support for that. Not sure if the zone-byte can just be extended by one, but that too would be easy to test as long as you have the hardware to do so. Without modification, the project could now do 2^8 thus 256 zones - if the lights allow.

> Are you planning a release of your app for the IOS platform? Australia is a BIG user of IOS.

No, I am not. I do not own any iOS devices and I have no experience developing for iOS. Neither am I  interested in owning or developing for Apple products. Personal preference. Sorry. Do feel free to port, though.
